package Pojo;
// Generated 28/03/2016 11:00:41 AM by Hibernate Tools 4.3.1



/**
 * PregConc generated by hbm2java
 */
public class PregConc  implements java.io.Serializable {


     private int idPregConc;
     private Concepto concepto;
     private Pregunta pregunta;

    public PregConc() {
    }

    public PregConc(int idPregConc, Pregunta pregunta, Concepto concepto) {
       this.idPregConc = idPregConc;
       this.pregunta = pregunta;
       this.concepto = concepto;
    }
   
    public int getIdPregConc() {
        return this.idPregConc;
    }
    
    public void setIdPregConc(int idPregConc) {
        this.idPregConc = idPregConc;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }



}


